### ISSUE TITLE
Some Lenovo and Oppo phone are not able to detect

### ISSUE THREAD

**Issue by nodeffect** [piwik/device-detector#5296]
Some Lenovo and Oppo phones are not able to detect. I'm using Oppo Phone X9006.

I think you need to add more models to the library ? Thanks!

**Comment by sgiehl** [comment]
Would you mind looking up the useragent on those devices. I can't add proper detections without knowing them.

**Comment by nodeffect** [comment]
Oppo Find 7a.... The user agent is this... Mozilla/5.0 (Linux; Android 4.3; X9006 Build/JLS36C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36

**Comment by nodeffect** [comment]
I think the chrome version is different ? cuz it's still not able to detect ?

**Comment by sgiehl** [comment]
Result of latest master:
```
user_agent: Mozilla/5.0 (Linux; Android 4.3; X9006 Build/JLS36C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36
os:
  name: Android
  short_name: AND
  version: 4.3
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 39.0.2171.93
  engine: Blink
device:
  type: smartphone
  brand: OP
  model: Find 7a
os_family: Android
browser_family: Chrome
```
