### ISSUE TITLE
Detect IE 12 

### ISSUE THREAD

**Issue by tzi** [piwik/device-detector#5303]
Hi!

Yesterday, the Microsoft team made a technical preview of Windows 10 and their new broswer for IE12. It will use a new rendering engine called [Edge](http://blogs.msdn.com/b/ie/archive/2014/11/11/living-on-the-edge-our-next-step-in-interoperability.aspx#10572654)! 

They also reveal their all shiny new UA string :fearful: 

```
Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0
```

Here is what the device-detector detect for now:

```
client:
  type: browser
  name: Chrome
  short_name: CH
  version: 36.0.1985.143
  engine: Blink
```

And it should be:

```
client:
  type: browser
  name: Internet Explorer
  short_name: IE
  version: 12.0
  engine: Edge
```

Here the [source](https://gist.github.com/jacobrossi/c9699b27df2f4e97c0bd).

Cheers,
Thomas.
