### ISSUE TITLE
Parsing user_agent for symbian os

### ISSUE THREAD

**Issue by rusikf** [piwik/device-detector#5324]
I am using ruby port of this library - https://github.com/podigee/device_detector, which doesn't change original regexpes yaml.

For this user_agent
```ruby
Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; Series 60/03.83; 9730) Opera 8.65 [ru]
```
Library return nil, but it is a mobile device.(device is not detected, because there is no pattern in yaml config)

Can you fix it ?

**Comment by sgiehl** [comment]
Current response from the php parsers is:
```
user_agent: 'Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; Series 60/03.83; 9730) Opera 8.65 [ru]'
os:
  name: Symbian OS Series 60
  short_name: S60
  version: 03.83
client:
  type: browser
  name: Opera
  short_name: OP
  version: 8.65
  engine: Presto
device:
  type:
  brand:
  model:
os_family: Symbian
browser_family: Opera
```

There is no device fragment in it, so we can't detect any specific device. In the php parsers ```isMobile``` should return ```true``` as SymbianOS is considered to be mobile.
What would you expect to be returned?
