### ISSUE TITLE
Missing detection for Samsung EG-2152 feature phone

### ISSUE THREAD

**Issue by yagooar** [piwik/device-detector#5327]
User agent: `SAMSUNG-GT-E2152/E2152XXJK2 NetFront/3.5 Profile/MIDP-2.0 Configuration/CLDC-1.1`
Phone details: http://www.gsmarena.com/samsung_e2152-3448.php

My proposed values:

Client name: `NetFront 3.5`
Client full version: `3.5`
OS name: `Samsung GT-E2152`
OS full version: `GT-E2152`
Device brand: `Samsung`
Device type: `feature phone`

What would be the best strategy for adding this phone?

**Comment by sgiehl** [comment]
Currently that useragent is detected as:
```
user_agent: SAMSUNG-GT-E2152/E2152XXJK2 NetFront/3.5 Profile/MIDP-2.0 Configuration/CLDC-1.1
os: [ ]
client:
  type: browser
  name: NetFront
  short_name: NF
  version: 3.5
  engine: NetFront
device:
  type: smartphone
  brand: SA
  model: GT-E2152
os_family: Unknown
browser_family: NetFront
```

Client ist correct. Device is detected, but it should be a feature phone instead of smartphone. I'll fix that.
