### ISSUE TITLE
Podcast client "Instacast" not detected

### ISSUE THREAD

**Issue by yagooar** [piwik/device-detector#5356]
Our business heavily relies on podcast clients, Instacast being one a pretty popular one, but it seems to be missing in DeviceDetector.

I just wanted to let you know that we added the following rules to our Ruby port:

```yaml
# regexes/client/mediaplayers.yml
- regex: 'Instacast\/([\d\.]+) CFNetwork\/([\d\.]+)'
  name: 'Instacast'
  version: '$1'
```

```yaml
# Tests/Parser/Client/fixtures/mediaplayer.yml
-
  user_agent: Instacast/2380 CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)
  client:
    type: mediaplayer
    name: Instacast
    version: "2380"
-
  user_agent: Instacast/4.1.2 CFNetwork/672.0.8 Darwin/14.0.0
  client:
    type: mediaplayer
    name: Instacast
    version: "4.1.2"
```
