### ISSUE TITLE
Custom user-agent OR detect LG TV

### ISSUE THREAD

**Issue by vergissberlin** [piwik/device-detector#5503]
**Hi,**

is it possible to ad custom user-agents? How I can do that?
All of my clients are smart TVs from LG but they are shown as _desktop_ in device type list.
I tried this way:
````
LG:
  regex: 'LGE'
  device: 'tv'
  models:
    - regex: 'Mozilla/5.0 (Linux; NetCast; U) AppleWwbKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.33 Safari/537.31 SmartTV/5.0'
      model: 'Cabin TV'
```
but unfortunately without success:
![LGE](https://api.monosnap.com/rpc/file/download?id=KcxXRvX0VaULc82HIHIeq8KTBPuT2f "LG")

André

**Comment by sgiehl** [comment]
Is `Mozilla/5.0 (Linux; NetCast; U) AppleWwbKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.33 Safari/537.31 SmartTV/5.0` the full useragent of those TVs? I'd add a general detection for those smart tvs then.

**Comment by vergissberlin** [comment]
@sgiehl Yes, the units all have the same user-agent. How did you added a general detection?

**Comment by ThaDafinser** [comment]
@vergissberlin check the *.yml files
https://github.com/piwik/device-detector/blob/master/regexes/device/televisions.yml#L97-L103

**Comment by vergissberlin** [comment]
@ThaDafinser Yes I did and I changed the user agent but unfortunately without success.
I found the file comment which says 

> ATTENTION: This file may only include tv user agents that contain 'HbbTV/([1-9]{1}(\.[0-9]{1}){1,2})

, but i can't find any regex for that.

**Is it possible** to add a custom user-agent like that in *televisions.yml*?
```
MyCustom:
  regex: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
  device: 'tv'
  models: ''
```
