### ISSUE TITLE
Dell smartphone false-positives

### ISSUE THREAD

**Issue by lewa** [piwik/device-detector#5560]
/regexes/device/mobiles.yml contains the following regex:

```
# Dell
Dell:
  regex: 'Dell|Venue|XCD35'
  device: 'smartphone'
```

In Italian the word "delle" is very common and is contained in some user agent strings. The above-mentioned regex identifies such user agents as Dell smartphones. Can Dell be replaced with Dell[^a-z] or Dell[ ;_\-] or something?

User agent example:

`Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; Corpo delle capitanerie di porto)`
