### ISSUE TITLE
Add screen resolution for mobile devices

### ISSUE THREAD

**Issue by aleksas** [piwik/device-detector#5563]
Would be great if for recognized mobile devices screen resolution would also be filled in automatically.
These pages might be helpful: http://mydevice.io/devices/ , http://viewportsizes.com/.

**Comment by sgiehl** [comment]
Yes that might be good, but Device Detector is currently not designed to do that.
We do not have specifications saved for each device but use regular expressions to detect various devices of the same brand.
Having specifications for each device would also make the detection much slower, so I don't think we will add that.

**Comment by GregOriol** [comment]
@sgiehl @mattab Might I suggest to reconsider this suggestion? It could be nice to have some more detailed information on mobile devices, not all specs, but:
* differentiate the device name from some model specifics (ex: some devices have some details like a year "GALAXY J5 (2015)"/"GALAXY J5 (2016)" or Wi-Fi/LTE "GALAXY S5"/"GALAXY S5 LTE+" or sometimes "Dual sim") => while it's interesting to have those detailed name for some use cases, it's not always useful for statistics and those details may/should be grouped intro the same device model => it could be another attribute like detailedModel or modelSpecifier
* having the screen size, in inches and the screen density, in dpis could allow for some nice display statistics

Of course those would have to be added to the yamls for the devices, which would be a long community work, but it would be a useful addition if it was possible!

**Comment by sgiehl** [comment]
I agree that some information like the year or parts like Dual Sim, LTE, WiFi is not useful in the model. 
I like the idea of moving that to an additional `modelSpecifier` or similar.

Screen size or screen density is something we won't add. We want to keep the detections as simple as possible. The are quite simple detections like:
```
# Woxter
Woxter:
  regex: 'Woxter[ _]([^/;]+) Build'
  device: 'tablet'
  model: '$1'
```
That's enough for detecting most of their devices. Adding a density or size would mean we would need to list every single device on the list, to check what exactly it is. Having thousands of devices in the list would make it a lot slower and harder to maintain as a lot devices are coming up each week. And that would be nothing I'm able to maintain.

**Comment by sanchezzzhak** [comment]
Should we reconsider this question again?
We can make a determination of the size of the screen in external files.

1 make a hash of devices based on tests
The data structure is as follows
```yml
Vivo: # brand
  V1934A: # model
    - screen_size: '1000x1000'
    - sim: 'dual sim'
```

To get this information, we can put the code in a separate class
So that it doesn't interfere with our current detection of device

Search by hash
```php
$dataSpecifier = $modelSpecifier['VIVO]['V1934A'] ?? null;
```

**Comment by mimmi20** [comment]
Then you should add the size (in inches) too, because current smart watches may have a higher resolution then older smartphones.

**Comment by sgiehl** [comment]
That might become a very big list if you want to provide such information for all devices. Not sure if it's worth the effort. Also reviewing and checking the new data will consume some more time...
Actually that might be something we could add in a new parser, that event won't need to be part of this repo. It should be simply possible to require another parser and add it using `addDeviceParser()` manually...

**Comment by sanchezzzhak** [comment]
let me try to do this in a separate repository.
I think I can automate this process.

**Comment by sanchezzzhak** [comment]
A year later, I still came back to this question
in my own fork https://github.com/sanchezzzhak/node-device-detector, I started supporting device sizes and other parameters. 

There is not enough data yet, but there will be more over time.

parse result
```js
{
  display: {
    size: '5.5', // in inches
    resolution: { width: '1080', height: '1920' },  // in pixels
    ratio: '16:9'
  },
  size: { width: '155.4', height: '75.2', thickness: '7.7' },  // in millimeters
  weight: '165',  // in grams
  release: '2017' // release or announcement 
}
```
fixture format (I had to abandon normalization, as it took up a lot of space)
```yml
asus:
  zenfone 2: 'DS=5.5;RS=1080x1920;RT=16:9;SZ=77.2x152.5x10.9;WT=170;RE=2015;'
  zenfone 2 laser: 'DS=5.0;RS=720x1280;RT=16:9;SZ=71.5x143.7x10.5;WT=140;RE=2015;'
  zenfone 2e: 'DS=5.0;RS=720x1280;RT=16:9;SZ=71.4x148.1x10.9;WT=155;RE=2015;'
  zenfone 4: 'DS=5.5;RS=1080x1920;RT=16:9;SZ=75.2x155.4x7.7;WT=165;RE=2017;'
  zenfone 5: 'DS=6.2;RS=11080x2246;RT=18.7:9;SZ=75.7x153x7.7;WT=165;RE=2018;'
  zenfone 5 lte: 'DS=5.0;RS=720x1280;RT=16:9;SZ=72.8x148.2x10.3;WT=145;RE=2014;'
  zenfone 5 lite: 'DS=6.0;RS=1080x2160;RT=18:9;SZ=76.2x160.6x7.8;WT=168;RE=2018;'
```
schema format for normalization:
```js
{
  DS: 'display.size',
  RS: 'display.resolution',
  RT: 'display.ratio',
  SZ: 'size',
  WT: 'weight',
  RE: 'release'
};
```
when more than 1k ~ devices are collected, I will add a pull request for php
