### ISSUE TITLE
android Edge browser on Windows Phone 10

### ISSUE THREAD

**Issue by gemal** [piwik/device-detector#5693]
`Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; HP; Elite x3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15`

I've scanned thousand of user agents from our site with your tool only only found this one that didn't get detected

**Comment by Findus23** [comment]
According to http://devicedetector.net it is detected as `Windows Phone 10.0` and `Microsoft Edge 15`. Am I right that you mean that it should also be detected as a `HP Elite x3`?

**Comment by gemal** [comment]
I dont have the very latest version of the detector so I have to update and test again. Sorry

**Comment by gemal** [comment]
I checked my code and we rely on `getDeviceName` which for this one is empty
Shoudn't it be mobile ?

**Comment by sgiehl** [comment]
I've added a better detection for HP devices. It will now be detected like this:
```
user_agent: Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; HP; Elite x3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15
os:
  name: Windows Phone
  short_name: WPH
  version: "10.0"
  platform: ""
client:
  type: browser
  name: Microsoft Edge
  short_name: PS
  version: "15"
  engine: Edge
  engine_version: "15"
device:
  type: smartphone
  brand: HP
  model: Elite x3
os_family: Windows Mobile
browser_family: Internet Explorer
```

btw. @Findus23  the reason why M$ started to add weird fragments to the user agent in IE11 might be the same as for Edge on mobile devices:  https://blogs.msdn.microsoft.com/ie/2014/07/31/the-mobile-web-should-just-work-for-everyone/
